import React, { useState } from 'react';
import { generateCraiyonImage } from '../api/craiyon';

function QuizPage() {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e) {
    e.preventDefault();
    setLoading(true);
    try {
      const img = await generateCraiyonImage(prompt);
      setImageUrl(img);
    } catch (error) {
      alert('Failed to generate image. See console.');
    }
    setLoading(false);
  }

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <input
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe your pixel art"
          required
        />
        <button type="submit" disabled={loading}>
          {loading ? 'Generating...' : 'Generate Image'}
        </button>
      </form>
      {imageUrl && (
        <div>
          <img src={imageUrl} alt="Generated by Craiyon" />
        </div>
      )}
    </div>
  );
}

export default QuizPage;
